-- Insert Sample Data for EU Region (Shard 2)
-- Run as bank_app user on Shard 2 (oracle-shard2)
-- This file inserts sample data for Europe region
-- User IDs will be auto-generated in range 10,000,001 - 20,000,000

SET SERVEROUTPUT ON

PROMPT ====================================
PROMPT Inserting Sample Data for EU Region (Shard 2)
PROMPT ====================================

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE

CONNECT bank_app/BankAppPass123@freepdb1

PROMPT Inserting EU region users (user_id auto-generated: 10M-20M)...

-- Insert EU region users - user_id is auto-generated by trigger
INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('jane_smith', 'jane.smith@example.com', 'Jane Smith', '+44-20-7123-4567', '10 Downing Street, London, UK', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('pierre_dupont', 'pierre.dupont@example.com', 'Pierre Dupont', '+33-1-2345-6789', '15 Rue de la Paix, Paris, France', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('hans_mueller', 'hans.mueller@example.com', 'Hans Mueller', '+49-30-1234-5678', 'Unter den Linden 1, Berlin, Germany', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('sophia_rossi', 'sophia.rossi@example.com', 'Sophia Rossi', '+39-02-1234-5678', 'Via Roma 5, Milan, Italy', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('carlos_rodriguez', 'carlos.rodriguez@example.com', 'Carlos Rodriguez', '+34-91-123-4567', 'Gran Via 1, Madrid, Spain', 'EU');
COMMIT;

-- Get the generated user IDs for reference
PROMPT Generated EU user IDs:
SELECT user_id, username, region FROM users ORDER BY user_id;

PROMPT Inserting EU region accounts (co-located with users)...

-- Insert accounts for EU region users
-- Accounts are co-located with users on the same shard
DECLARE
    v_user1_id NUMBER;  -- jane_smith
    v_user2_id NUMBER;  -- pierre_dupont
    v_user3_id NUMBER;  -- hans_mueller
    v_user4_id NUMBER;  -- sophia_rossi
    v_user5_id NUMBER;  -- carlos_rodriguez
    v_acc1_id NUMBER;
    v_acc2_id NUMBER;
    v_acc3_id NUMBER;
BEGIN
    -- Get user IDs that were auto-generated
    SELECT user_id INTO v_user1_id FROM users WHERE username = 'jane_smith' AND region = 'EU';
    SELECT user_id INTO v_user2_id FROM users WHERE username = 'pierre_dupont' AND region = 'EU';
    SELECT user_id INTO v_user3_id FROM users WHERE username = 'hans_mueller' AND region = 'EU';
    SELECT user_id INTO v_user4_id FROM users WHERE username = 'sophia_rossi' AND region = 'EU';
    SELECT user_id INTO v_user5_id FROM users WHERE username = 'carlos_rodriguez' AND region = 'EU';
    
    -- Insert accounts for jane_smith
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC008', 'CHECKING', 7500.00, 'USD', 'EU');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC009', 'SAVINGS', 30000.00, 'USD', 'EU');
    
    -- Insert accounts for pierre_dupont
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC010', 'CHECKING', 8500.00, 'USD', 'EU');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC011', 'SAVINGS', 55000.00, 'USD', 'EU');
    
    -- Insert accounts for hans_mueller
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user3_id, 'ACC012', 'CHECKING', 9200.00, 'USD', 'EU');
    
    -- Insert accounts for sophia_rossi
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user4_id, 'ACC013', 'SAVINGS', 68000.00, 'USD', 'EU');
    
    -- Insert accounts for carlos_rodriguez
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user5_id, 'ACC014', 'CHECKING', 6200.00, 'USD', 'EU');
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Inserting sample transactions for EU accounts...');
    
    -- Insert sample transactions for EU accounts
    -- Transactions are co-located with accounts on same shard
    -- Using account_number directly (ACC008, ACC009, etc.)
    
    -- Deposit for jane_smith's checking account (ACC008)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC008', NULL, 'ACC008', 'DEPOSIT', 7500.00, 'USD', 'COMPLETED', 'Initial deposit');
    
    -- Transfer from checking (ACC008) to savings (ACC009)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC008', 'ACC008', 'ACC009', 'TRANSFER', 3000.00, 'USD', 'COMPLETED', 'Transfer to savings');
    
    -- Deposit for pierre_dupont's checking account (ACC010)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC010', NULL, 'ACC010', 'DEPOSIT', 8500.00, 'USD', 'COMPLETED', 'Initial deposit');
    
    -- Withdrawal for hans_mueller's checking account (ACC012)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC012', 'ACC012', NULL, 'WITHDRAWAL', 500.00, 'USD', 'COMPLETED', 'ATM withdrawal');
    
    COMMIT;
END;
/

-- Display generated account IDs
PROMPT Generated EU account IDs:
SELECT account_id, user_id, account_number, account_type, balance, region 
FROM accounts 
ORDER BY account_id;

-- Display transaction summary
PROMPT Transaction summary:
SELECT 
    transaction_type,
    COUNT(*) AS count,
    SUM(amount) AS total_amount
FROM transactions
GROUP BY transaction_type
ORDER BY transaction_type;

PROMPT ====================================
PROMPT EU region sample data inserted successfully!
PROMPT ====================================
