-- Insert Sample Data for APAC Region (Shard 3)
-- Run as bank_app user on Shard 3 (oracle-shard3)
-- This file inserts sample data for Asia Pacific region
-- User IDs will be auto-generated in range 20,000,001 - 30,000,000

PROMPT ====================================
PROMPT Inserting Sample Data for APAC Region (Shard 3)
PROMPT ====================================

CONNECT bank_app/BankAppPass123@FREEPDB1

PROMPT Inserting APAC region users (user_id auto-generated: 20M-30M)...

-- Insert APAC region users - user_id is auto-generated by trigger
INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('lee_wong', 'lee.wong@example.com', 'Lee Wong', '+86-10-1234-5678', '1 Chang\'an Avenue, Beijing, China', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('yuki_tanaka', 'yuki.tanaka@example.com', 'Yuki Tanaka', '+81-3-1234-5678', '1-1-1 Marunouchi, Tokyo, Japan', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('raj_kumar', 'raj.kumar@example.com', 'Raj Kumar', '+91-11-2345-6789', 'Connaught Place, New Delhi, India', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('wei_zhang', 'wei.zhang@example.com', 'Wei Zhang', '+65-6-123-4567', '1 Marina Bay, Singapore', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('min_choi', 'min.choi@example.com', 'Min Choi', '+82-2-123-4567', '1 Jongno-gu, Seoul, South Korea', 'APAC');
COMMIT;

-- Get the generated user IDs for reference
PROMPT Generated APAC user IDs:
SELECT user_id, username, region FROM users ORDER BY user_id;

PROMPT Inserting APAC region accounts (co-located with users)...

-- Insert accounts for APAC region users
-- Accounts are co-located with users on the same shard
DECLARE
    v_user1_id NUMBER;  -- lee_wong
    v_user2_id NUMBER;  -- yuki_tanaka
    v_user3_id NUMBER;  -- raj_kumar
    v_user4_id NUMBER;  -- wei_zhang
    v_user5_id NUMBER;  -- min_choi
    v_acc1_id NUMBER;
    v_acc2_id NUMBER;
    v_acc3_id NUMBER;
BEGIN
    -- Get user IDs that were auto-generated
    SELECT user_id INTO v_user1_id FROM users WHERE username = 'lee_wong' AND region = 'APAC';
    SELECT user_id INTO v_user2_id FROM users WHERE username = 'yuki_tanaka' AND region = 'APAC';
    SELECT user_id INTO v_user3_id FROM users WHERE username = 'raj_kumar' AND region = 'APAC';
    SELECT user_id INTO v_user4_id FROM users WHERE username = 'wei_zhang' AND region = 'APAC';
    SELECT user_id INTO v_user5_id FROM users WHERE username = 'min_choi' AND region = 'APAC';
    
    -- Insert accounts for lee_wong
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC-APAC-001', 'CHECKING', 15000.00, 'CNY', 'APAC');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC-APAC-002', 'SAVINGS', 90000.00, 'CNY', 'APAC');
    
    -- Insert accounts for yuki_tanaka
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC-APAC-003', 'CHECKING', 18000.00, 'JPY', 'APAC');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC-APAC-004', 'SAVINGS', 120000.00, 'JPY', 'APAC');
    
    -- Insert accounts for raj_kumar
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user3_id, 'ACC-APAC-005', 'CHECKING', 25000.00, 'INR', 'APAC');
    
    -- Insert accounts for wei_zhang
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user4_id, 'ACC-APAC-006', 'SAVINGS', 75000.00, 'SGD', 'APAC');
    
    -- Insert accounts for min_choi
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user5_id, 'ACC-APAC-007', 'CHECKING', 14000.00, 'KRW', 'APAC');
    
    COMMIT;
    
    -- Get account IDs for transactions
    SELECT MIN(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user1_id;
    SELECT MIN(account_id) INTO v_acc2_id FROM accounts WHERE user_id = v_user2_id;
    SELECT MIN(account_id) INTO v_acc3_id FROM accounts WHERE user_id = v_user3_id;
    
    PROMPT Inserting sample transactions...
    
    -- Insert sample transactions for APAC accounts
    -- Transactions are co-located with accounts on same shard
    
    -- Deposit for lee_wong's checking account
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (NULL, v_acc1_id, 'DEPOSIT', 15000.00, 'CNY', 'COMPLETED', 'Initial deposit');
    
    -- Transfer from checking to savings
    SELECT MAX(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user1_id AND account_type = 'SAVINGS';
    SELECT MIN(account_id) INTO v_acc2_id FROM accounts WHERE user_id = v_user1_id AND account_type = 'CHECKING';
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (v_acc2_id, v_acc1_id, 'TRANSFER', 5000.00, 'CNY', 'COMPLETED', 'Transfer to savings');
    
    -- Deposit for yuki_tanaka
    SELECT MIN(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user2_id;
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (NULL, v_acc1_id, 'DEPOSIT', 18000.00, 'JPY', 'COMPLETED', 'Initial deposit');
    
    -- Withdrawal for raj_kumar
    SELECT MIN(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user3_id;
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (v_acc1_id, NULL, 'WITHDRAWAL', 5000.00, 'INR', 'COMPLETED', 'ATM withdrawal');
    
    COMMIT;
END;
/

-- Display generated account IDs
PROMPT Generated APAC account IDs:
SELECT account_id, user_id, account_number, account_type, balance, region 
FROM accounts 
ORDER BY account_id;

-- Display transaction summary
PROMPT Transaction summary:
SELECT 
    transaction_type,
    COUNT(*) AS count,
    SUM(amount) AS total_amount
FROM transactions
GROUP BY transaction_type
ORDER BY transaction_type;

PROMPT ====================================
PROMPT APAC region sample data inserted successfully!
PROMPT ====================================
