-- Insert Sample Data for NA Region (Shard 1)
-- Run as bank_app user on Shard 1 (oracle-shard1)
-- This file inserts sample data for North America region
-- User IDs will be auto-generated in range 1 - 10,000,000

SET SERVEROUTPUT ON

PROMPT ====================================
PROMPT Inserting Sample Data for NA Region (Shard 1)
PROMPT ====================================

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE

CONNECT bank_app/BankAppPass123@freepdb1

PROMPT Inserting NA region users (user_id auto-generated: 1-10M)...

-- Insert NA region users - user_id is auto-generated by trigger
INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('john_doe', 'john.doe@example.com', 'John Doe', '555-0101', '123 Main St, New York, NY', 'NA');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('maria_garcia', 'maria.garcia@example.com', 'Maria Garcia', '555-0102', '456 Oak Ave, Los Angeles, CA', 'NA');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('robert_smith', 'robert.smith@example.com', 'Robert Smith', '555-0103', '789 Pine Rd, Chicago, IL', 'NA');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('jennifer_wilson', 'jennifer.wilson@example.com', 'Jennifer Wilson', '555-0104', '321 Elm St, Houston, TX', 'NA');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('david_brown', 'david.brown@example.com', 'David Brown', '555-0105', '654 Maple Dr, Phoenix, AZ', 'NA');
COMMIT;

-- Get the generated user IDs for reference
PROMPT Generated NA user IDs:
SELECT user_id, username, region FROM users ORDER BY user_id;

PROMPT Inserting NA region accounts (co-located with users)...

-- Insert accounts for NA region users
-- Accounts are co-located with users on the same shard
DECLARE
    v_user1_id NUMBER;  -- john_doe
    v_user2_id NUMBER;  -- maria_garcia
    v_user3_id NUMBER;  -- robert_smith
    v_user4_id NUMBER;  -- jennifer_wilson
    v_user5_id NUMBER;  -- david_brown
BEGIN
    -- Get user IDs that were auto-generated
    SELECT user_id INTO v_user1_id FROM users WHERE username = 'john_doe' AND region = 'NA';
    SELECT user_id INTO v_user2_id FROM users WHERE username = 'maria_garcia' AND region = 'NA';
    SELECT user_id INTO v_user3_id FROM users WHERE username = 'robert_smith' AND region = 'NA';
    SELECT user_id INTO v_user4_id FROM users WHERE username = 'jennifer_wilson' AND region = 'NA';
    SELECT user_id INTO v_user5_id FROM users WHERE username = 'david_brown' AND region = 'NA';
    
    -- Insert accounts for john_doe
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC001', 'CHECKING', 5000.00, 'USD', 'NA');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC002', 'SAVINGS', 25000.00, 'USD', 'NA');
    
    -- Insert accounts for maria_garcia
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC003', 'CHECKING', 3500.00, 'USD', 'NA');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC004', 'SAVINGS', 45000.00, 'USD', 'NA');
    
    -- Insert accounts for robert_smith
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user3_id, 'ACC005', 'CHECKING', 12000.00, 'USD', 'NA');
    
    -- Insert accounts for jennifer_wilson
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user4_id, 'ACC006', 'SAVINGS', 80000.00, 'USD', 'NA');
    
    -- Insert accounts for david_brown
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user5_id, 'ACC007', 'CHECKING', 7500.00, 'USD', 'NA');
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Inserting sample transactions for NA accounts...');
    
    -- Insert sample transactions for NA accounts
    -- Transactions are co-located with accounts on same shard
    -- Using account_number directly (ACC001, ACC002, etc.)
    
    -- Deposit for john_doe's checking account (ACC001)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC001', NULL, 'ACC001', 'DEPOSIT', 5000.00, 'USD', 'COMPLETED', 'Initial deposit');
    
    -- Transfer from checking (ACC001) to savings (ACC002)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC001', 'ACC001', 'ACC002', 'TRANSFER', 2000.00, 'USD', 'COMPLETED', 'Transfer to savings');
    
    -- Deposit for maria_garcia's checking account (ACC003)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC003', NULL, 'ACC003', 'DEPOSIT', 3500.00, 'USD', 'COMPLETED', 'Initial deposit');
    
    -- Withdrawal for robert_smith's checking account (ACC005)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC005', 'ACC005', NULL, 'WITHDRAWAL', 500.00, 'USD', 'COMPLETED', 'ATM withdrawal');
    
    COMMIT;
END;
/

-- Display generated account IDs
PROMPT Generated NA account IDs:
SELECT account_id, user_id, account_number, account_type, balance, region 
FROM accounts 
ORDER BY account_id;

-- Display transaction summary
PROMPT Transaction summary:
SELECT 
    transaction_type,
    COUNT(*) AS count,
    SUM(amount) AS total_amount
FROM transactions
GROUP BY transaction_type
ORDER BY transaction_type;

PROMPT ====================================
PROMPT NA region sample data inserted successfully!
PROMPT ====================================
