-- Insert Sample Data for APAC Region (Shard 3)
-- Run as bank_app user on Shard 3 (oracle-shard3)
-- This file inserts sample data for Asia Pacific region
-- User IDs will be auto-generated in range 20,000,001 - 30,000,000

SET SERVEROUTPUT ON

PROMPT ====================================
PROMPT Inserting Sample Data for APAC Region (Shard 3)
PROMPT ====================================

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE

CONNECT bank_app/BankAppPass123@freepdb1

PROMPT Inserting APAC region users (user_id auto-generated: 20M-30M)...

-- Insert APAC region users - user_id is auto-generated by trigger
INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('lee_wong', 'lee.wong@example.com', 'Lee Wong', '+86-10-1234-5678', '1 Chang''an Avenue, Beijing, China', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('yuki_tanaka', 'yuki.tanaka@example.com', 'Yuki Tanaka', '+81-3-1234-5678', '1-1-1 Marunouchi, Tokyo, Japan', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('raj_kumar', 'raj.kumar@example.com', 'Raj Kumar', '+91-11-2345-6789', 'Connaught Place, New Delhi, India', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('wei_zhang', 'wei.zhang@example.com', 'Wei Zhang', '+65-6-123-4567', '1 Marina Bay, Singapore', 'APAC');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('min_choi', 'min.choi@example.com', 'Min Choi', '+82-2-123-4567', '1 Jongno-gu, Seoul, South Korea', 'APAC');
COMMIT;

-- Get the generated user IDs for reference
PROMPT Generated APAC user IDs:
SELECT user_id, username, region FROM users ORDER BY user_id;

PROMPT Inserting APAC region accounts (co-located with users)...

-- Insert accounts for APAC region users
-- Accounts are co-located with users on the same shard
DECLARE
    v_user1_id NUMBER;  -- lee_wong
    v_user2_id NUMBER;  -- yuki_tanaka
    v_user3_id NUMBER;  -- raj_kumar
    v_user4_id NUMBER;  -- wei_zhang
    v_user5_id NUMBER;  -- min_choi
    v_acc1_id NUMBER;
    v_acc2_id NUMBER;
    v_acc3_id NUMBER;
BEGIN
    -- Get user IDs that were auto-generated
    SELECT user_id INTO v_user1_id FROM users WHERE username = 'lee_wong' AND region = 'APAC';
    SELECT user_id INTO v_user2_id FROM users WHERE username = 'yuki_tanaka' AND region = 'APAC';
    SELECT user_id INTO v_user3_id FROM users WHERE username = 'raj_kumar' AND region = 'APAC';
    SELECT user_id INTO v_user4_id FROM users WHERE username = 'wei_zhang' AND region = 'APAC';
    SELECT user_id INTO v_user5_id FROM users WHERE username = 'min_choi' AND region = 'APAC';
    
    -- Insert accounts for lee_wong
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC015', 'CHECKING', 15000.00, 'USD', 'APAC');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC016', 'SAVINGS', 90000.00, 'USD', 'APAC');
    
    -- Insert accounts for yuki_tanaka
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC017', 'CHECKING', 18000.00, 'USD', 'APAC');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC018', 'SAVINGS', 120000.00, 'USD', 'APAC');
    
    -- Insert accounts for raj_kumar
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user3_id, 'ACC019', 'CHECKING', 25000.00, 'USD', 'APAC');
    
    -- Insert accounts for wei_zhang
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user4_id, 'ACC020', 'SAVINGS', 75000.00, 'USD', 'APAC');
    
    -- Insert accounts for min_choi
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user5_id, 'ACC021', 'CHECKING', 14000.00, 'USD', 'APAC');
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Inserting sample transactions for APAC accounts...');
    
    -- Insert sample transactions for APAC accounts
    -- Transactions are co-located with accounts on same shard
    -- Using account_number directly (ACC015, ACC016, etc.)
    
    -- Deposit for lee_wong's checking account (ACC015)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC015', NULL, 'ACC015', 'DEPOSIT', 15000.00, 'USD', 'COMPLETED', 'Initial deposit');
    
    -- Transfer from checking (ACC015) to savings (ACC016)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC015', 'ACC015', 'ACC016', 'TRANSFER', 5000.00, 'USD', 'COMPLETED', 'Transfer to savings');
    
    -- Deposit for yuki_tanaka's checking account (ACC017)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC017', NULL, 'ACC017', 'DEPOSIT', 18000.00, 'USD', 'COMPLETED', 'Initial deposit');
    
    -- Withdrawal for raj_kumar's checking account (ACC019)
    INSERT INTO transactions (account_number, from_account_number, to_account_number, transaction_type, amount, currency, status, description)
    VALUES ('ACC019', 'ACC019', NULL, 'WITHDRAWAL', 5000.00, 'USD', 'COMPLETED', 'ATM withdrawal');
    
    COMMIT;
END;
/

-- Display generated account IDs
PROMPT Generated APAC account IDs:
SELECT account_id, user_id, account_number, account_type, balance, region 
FROM accounts 
ORDER BY account_id;

-- Display transaction summary
PROMPT Transaction summary:
SELECT 
    transaction_type,
    COUNT(*) AS count,
    SUM(amount) AS total_amount
FROM transactions
GROUP BY transaction_type
ORDER BY transaction_type;

PROMPT ====================================
PROMPT APAC region sample data inserted successfully!
PROMPT ====================================
