-- Insert Sample Data for EU Region (Shard 2)
-- Run as bank_app user on Shard 2 (oracle-shard2)
-- This file inserts sample data for Europe region
-- User IDs will be auto-generated in range 10,000,001 - 20,000,000

PROMPT ====================================
PROMPT Inserting Sample Data for EU Region (Shard 2)
PROMPT ====================================

CONNECT bank_app/BankAppPass123@FREEPDB1

PROMPT Inserting EU region users (user_id auto-generated: 10M-20M)...

-- Insert EU region users - user_id is auto-generated by trigger
INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('jane_smith', 'jane.smith@example.com', 'Jane Smith', '+44-20-7123-4567', '10 Downing Street, London, UK', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('pierre_dupont', 'pierre.dupont@example.com', 'Pierre Dupont', '+33-1-2345-6789', '15 Rue de la Paix, Paris, France', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('hans_mueller', 'hans.mueller@example.com', 'Hans Mueller', '+49-30-1234-5678', 'Unter den Linden 1, Berlin, Germany', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('sophia_rossi', 'sophia.rossi@example.com', 'Sophia Rossi', '+39-02-1234-5678', 'Via Roma 5, Milan, Italy', 'EU');
COMMIT;

INSERT INTO users (username, email, full_name, phone, address, region) 
VALUES ('carlos_rodriguez', 'carlos.rodriguez@example.com', 'Carlos Rodriguez', '+34-91-123-4567', 'Gran Via 1, Madrid, Spain', 'EU');
COMMIT;

-- Get the generated user IDs for reference
PROMPT Generated EU user IDs:
SELECT user_id, username, region FROM users ORDER BY user_id;

PROMPT Inserting EU region accounts (co-located with users)...

-- Insert accounts for EU region users
-- Accounts are co-located with users on the same shard
DECLARE
    v_user1_id NUMBER;  -- jane_smith
    v_user2_id NUMBER;  -- pierre_dupont
    v_user3_id NUMBER;  -- hans_mueller
    v_user4_id NUMBER;  -- sophia_rossi
    v_user5_id NUMBER;  -- carlos_rodriguez
    v_acc1_id NUMBER;
    v_acc2_id NUMBER;
    v_acc3_id NUMBER;
BEGIN
    -- Get user IDs that were auto-generated
    SELECT user_id INTO v_user1_id FROM users WHERE username = 'jane_smith' AND region = 'EU';
    SELECT user_id INTO v_user2_id FROM users WHERE username = 'pierre_dupont' AND region = 'EU';
    SELECT user_id INTO v_user3_id FROM users WHERE username = 'hans_mueller' AND region = 'EU';
    SELECT user_id INTO v_user4_id FROM users WHERE username = 'sophia_rossi' AND region = 'EU';
    SELECT user_id INTO v_user5_id FROM users WHERE username = 'carlos_rodriguez' AND region = 'EU';
    
    -- Insert accounts for jane_smith
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC-EU-001', 'CHECKING', 7500.00, 'GBP', 'EU');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user1_id, 'ACC-EU-002', 'SAVINGS', 30000.00, 'GBP', 'EU');
    
    -- Insert accounts for pierre_dupont
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC-EU-003', 'CHECKING', 8500.00, 'EUR', 'EU');
    
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user2_id, 'ACC-EU-004', 'SAVINGS', 55000.00, 'EUR', 'EU');
    
    -- Insert accounts for hans_mueller
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user3_id, 'ACC-EU-005', 'CHECKING', 9200.00, 'EUR', 'EU');
    
    -- Insert accounts for sophia_rossi
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user4_id, 'ACC-EU-006', 'SAVINGS', 68000.00, 'EUR', 'EU');
    
    -- Insert accounts for carlos_rodriguez
    INSERT INTO accounts (user_id, account_number, account_type, balance, currency, region)
    VALUES (v_user5_id, 'ACC-EU-007', 'CHECKING', 6200.00, 'EUR', 'EU');
    
    COMMIT;
    
    -- Get account IDs for transactions
    SELECT MIN(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user1_id;
    SELECT MIN(account_id) INTO v_acc2_id FROM accounts WHERE user_id = v_user2_id;
    SELECT MIN(account_id) INTO v_acc3_id FROM accounts WHERE user_id = v_user3_id;
    
    PROMPT Inserting sample transactions...
    
    -- Insert sample transactions for EU accounts
    -- Transactions are co-located with accounts on same shard
    
    -- Deposit for jane_smith's checking account
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (NULL, v_acc1_id, 'DEPOSIT', 7500.00, 'GBP', 'COMPLETED', 'Initial deposit');
    
    -- Transfer from checking to savings
    SELECT MAX(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user1_id AND account_type = 'SAVINGS';
    SELECT MIN(account_id) INTO v_acc2_id FROM accounts WHERE user_id = v_user1_id AND account_type = 'CHECKING';
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (v_acc2_id, v_acc1_id, 'TRANSFER', 3000.00, 'GBP', 'COMPLETED', 'Transfer to savings');
    
    -- Deposit for pierre_dupont
    SELECT MIN(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user2_id;
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (NULL, v_acc1_id, 'DEPOSIT', 8500.00, 'EUR', 'COMPLETED', 'Initial deposit');
    
    -- Withdrawal for hans_mueller
    SELECT MIN(account_id) INTO v_acc1_id FROM accounts WHERE user_id = v_user3_id;
    INSERT INTO transactions (from_account_id, to_account_id, transaction_type, amount, currency, status, description)
    VALUES (v_acc1_id, NULL, 'WITHDRAWAL', 500.00, 'EUR', 'COMPLETED', 'ATM withdrawal');
    
    COMMIT;
END;
/

-- Display generated account IDs
PROMPT Generated EU account IDs:
SELECT account_id, user_id, account_number, account_type, balance, region 
FROM accounts 
ORDER BY account_id;

-- Display transaction summary
PROMPT Transaction summary:
SELECT 
    transaction_type,
    COUNT(*) AS count,
    SUM(amount) AS total_amount
FROM transactions
GROUP BY transaction_type
ORDER BY transaction_type;

PROMPT ====================================
PROMPT EU region sample data inserted successfully!
PROMPT ====================================
